# Generated by Django 5.1.6 on 2025-08-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
